# https://github.com/golangci/golangci-lint/blob/master/.golangci.reference.yml

run:
  timeout: 5m
  modules-download-mode: readonly
  tests: false
  go: '1.15'

linters:
  enable:
    - errcheck
    - goimports
    - revive
    - govet
    - staticcheck
    - gosimple
  disable:
    - unused

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  new-from-rev: master

linters-settings:
  staticcheck:
    # SAxxxx checks in https://staticcheck.io/docs/configuration/options/#checks
    # Default value: ["all", "-ST1000", "-ST1003", "-ST1016", "-ST1020", "-ST1021", "-ST1022"]
    checks:
      # default checks
      - "all"
      - "-ST1000"
      - "-ST1003"
      - "-ST1016"
      - "-ST1020"
      - "-ST1021"
      - "-ST1022"
      # other checks
      - "-SA1019"  # Enable using a deprecated function, variable, constant or field. For compatibility reasons.
  goimports:
    local-prefixes: github.com/aliyun/aliyun-odps-go-sdk
