package odps_test

import (
	"github.com/aliyun/aliyun-odps-go-sdk/odps"
	"github.com/aliyun/aliyun-odps-go-sdk/odps/datatype"
	"github.com/aliyun/aliyun-odps-go-sdk/odps/tableschema"
	"log"
	"testing"
)

func TestTables_CreateNormalTable(t *testing.T) {

	column1 := tableschema.NewColumnBuilder("c1", datatype.TinyIntType).NotNull().Build()
	column2 := tableschema.NewColumnBuilder("c2", datatype.StringType).DefaultValue("'default'").Build()

	err := odps.NewTableCreator(odpsIns, odps.TableId("go_sdk_regression_testing", "default", "testTable"),
		[]tableschema.Column{column1, column2}).WithComment("generated by tableCreator").IfNotExists().Debug().Create()
	if err != nil {
		log.Fatalf("Failed to create table: %v", err) // 使用 Fatalf
	}
}

func TestTables_CreatePartitionedTable(t *testing.T) {

	column1 := tableschema.NewColumnBuilder("c1", datatype.TinyIntType).NotNull().Build()
	column2 := tableschema.NewColumnBuilder("c2", datatype.StringType).DefaultValue("'default'").Build()

	partitionColumn := tableschema.NewColumnBuilder("p1", datatype.StringType).Build()

	err := odps.NewTableCreator(odpsIns,
		odps.TableId("go_sdk_regression_testing", "default", "testTable2"),
		[]tableschema.Column{column1, column2},
	).
		PartitionColumns([]tableschema.Column{partitionColumn}).
		WithComment("generated by tableCreator").
		IfNotExists().
		Debug().
		Create()
	if err != nil {
		log.Fatalf("Failed to create table: %v", err) // 使用 Fatalf
	}
}

func TestTables_CreateTransactionTable(t *testing.T) {

	column1 := tableschema.NewColumnBuilder("c1", datatype.TinyIntType).NotNull().Build()
	column2 := tableschema.NewColumnBuilder("c2", datatype.BigIntType).NotNull().Build()
	column3 := tableschema.NewColumnBuilder("c3", datatype.StringType).DefaultValue("'default'").Build()
	column4 := tableschema.NewColumnBuilder("c4", datatype.DateTimeType).Build()

	partitionColumn := tableschema.NewColumnBuilder("p1", datatype.StringType).Build()

	err := odps.NewTableCreator(odpsIns,
		odps.TableId("go_sdk_regression_testing", "default", "testTable3"),
		[]tableschema.Column{column1, column2, column3, column4},
	).
		PartitionColumns([]tableschema.Column{partitionColumn}).
		WithComment("generated by tableCreator").
		IfNotExists().
		TransactionTable().
		WithPrimaryKeys([]string{"c1", "c2"}).
		Debug().
		Create()
	if err != nil {
		log.Fatalf("Failed to create table: %v", err) // 使用 Fatalf
	}
}
