package odps_test

import (
	"github.com/aliyun/aliyun-odps-go-sdk/odps"
	account2 "github.com/aliyun/aliyun-odps-go-sdk/odps/account"
	"github.com/aliyun/aliyun-odps-go-sdk/odps/datatype"
	"github.com/aliyun/aliyun-odps-go-sdk/odps/restclient"
	"github.com/aliyun/aliyun-odps-go-sdk/odps/tableschema"
	"log"
	"testing"
)

func setup() {
	account = account2.AliyunAccountFromEnv()
	endpoint = restclient.LoadEndpointFromEnv()
	odpsIns = odps.NewOdps(account, endpoint)
	odpsIns.SetDefaultProjectName("go_sdk_regression_testing")
}

func TestNewTableCreator(t *testing.T) {
	setup() // 确保运行 setup() 函数

	column1 := tableschema.NewColumnBuilder("c1", datatype.TinyIntType).NotNull().Build()
	column2 := tableschema.NewColumnBuilder("c2", datatype.StringType).DefaultValue("'default'").Build()

	err := odps.NewTableCreator(odpsIns, odps.TableId("go_sdk_regression_testing", "default", "testTable"),
		[]tableschema.Column{column1, column2}).WithComment("generated by tableCreator").IfNotExists().Debug().Create()
	if err != nil {
		log.Fatalf("Failed to create table: %v", err) // 使用 Fatalf
	}
}
